services:
  postgres:
    image: postgres:16
    container_name: pricewise-db
    environment:
      POSTGRES_DB: pricewise
      POSTGRES_USER: pricewise
      POSTGRES_PASSWORD: pricewise123
    ports:
      - "5432:5432"
    volumes:
      - pricewise_data:/var/lib/postgresql/data

volumes:
  pricewise_data: